In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
test=pd.read_csv("/workspaces/house-price-prediction/test (1).csv")

In [7]:
test.sample()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
401,1862,90,RL,NaN,11855,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,10,2009,WD,Normal

In [8]:
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1459 non-null   int64
 1   MSSubClass     1459 non-null   int64
 2   MSZoning       1455 non-null   str
 3   LotFrontage    1232 non-null   float64
 4   LotArea        1459 non-null   int64
 5   Street         1459 non-null   str
 6   Alley          107 non-null    str
 7   LotShape       1459 non-null   str
 8   LandContour    1459 non-null   str
 9   Utilities      1457 non-null   str
 10  LotConfig      1459 non-null   str
 11  LandSlope      1459 non-null   str
 12  Neighborhood   1459 non-null   str
 13  Condition1     1459 non-null   str
 14  Condition2     1459 non-null   str
 15  BldgType       1459 non-null   str
 16  HouseStyle     1459 non-null   str
 17  OverallQual    1459 non-null   int64
 18  OverallCond    1459 non-null   int64
 19  YearBuilt      1459 non-null   int64
 20  YearRemodAdd   1459 non-null   int64
 21  RoofStyle      1459 non-null   str
 22  RoofMatl       1459 non-null   str
 23  Exterior1st    1458 non-null   str
 24  Exterior2nd    1458 non-null   str
 25  MasVnrType     565 non-null    str
 26  MasVnrArea     1444 non-null   float64
 27  ExterQual      1459 non-null   str
 28  ExterCond      1459 non-null   str
 29  Foundation     1459 non-null   str
 30  BsmtQual       1415 non-null   str
 31  BsmtCond       1414 non-null   str
 32  BsmtExposure   1415 non-null   str
 33  BsmtFinType1   1417 non-null   str
 34  BsmtFinSF1     1458 non-null   float64
 35  BsmtFinType2   1417 non-null   str
 36  BsmtFinSF2     1458 non-null   float64
 37  BsmtUnfSF      1458 non-null   float64
 38  TotalBsmtSF    1458 non-null   float64
 39  Heating        1459 non-null   str
 40  HeatingQC      1459 non-null   str
 41  CentralAir     1459 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1459 non-null   int64
 44  2ndFlrSF       1459 non-null   int64
 45  LowQualFinSF   1459 non-null   int64
 46  GrLivArea      1459 non-null   int64
 47  BsmtFullBath   1457 non-null   float64
 48  BsmtHalfBath   1457 non-null   float64
 49  FullBath       1459 non-null   int64
 50  HalfBath       1459 non-null   int64
 51  BedroomAbvGr   1459 non-null   int64
 52  KitchenAbvGr   1459 non-null   int64
 53  KitchenQual    1458 non-null   str
 54  TotRmsAbvGrd   1459 non-null   int64
 55  Functional     1457 non-null   str
 56  Fireplaces     1459 non-null   int64
 57  FireplaceQu    729 non-null    str
 58  GarageType     1383 non-null   str
 59  GarageYrBlt    1381 non-null   float64
 60  GarageFinish   1381 non-null   str
 61  GarageCars     1458 non-null   float64
 62  GarageArea     1458 non-null   float64
 63  GarageQual     1381 non-null   str
 64  GarageCond     1381 non-null   str
 65  PavedDrive     1459 non-null   str
 66  WoodDeckSF     1459 non-null   int64
 67  OpenPorchSF    1459 non-null   int64
 68  EnclosedPorch  1459 non-null   int64
 69  3SsnPorch      1459 non-null   int64
 70  ScreenPorch    1459 non-null   int64
 71  PoolArea       1459 non-null   int64
 72  PoolQC         3 non-null      str
 73  Fence          290 non-null    str
 74  MiscFeature    51 non-null     str
 75  MiscVal        1459 non-null   int64
 76  MoSold         1459 non-null   int64
 77  YrSold         1459 non-null   int64
 78  SaleType       1458 non-null   str
 79  SaleCondition  1459 non-null   str
dtypes: float64(11), int64(26), str(43)
memory usage: 912.0 KB

In [9]:
test.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [10]:
null_percentage=(test.isnull().sum()/len(test))*100
print(null_percentage)

Id                0.000000
MSSubClass        0.000000
MSZoning          0.274160
LotFrontage      15.558602
LotArea           0.000000
                   ...
MiscVal           0.000000
MoSold            0.000000
YrSold            0.000000
SaleType          0.068540
SaleCondition     0.000000
Length: 80, dtype: float64

In [11]:
null_percentage=(test.isnull().sum()/len(test))*100 # find % of null values
print(null_percentage[null_percentage > 80])  # find % above 80%

Alley          92.666210
PoolQC         99.794380
Fence          80.123372
MiscFeature    96.504455
dtype: float64

In [21]:

test.drop(columns=["Alley", "PoolQC", "Fence", "MiscFeature"])

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,120,0,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,IR1,Lvl,AllPub,Corner,...,36,0,0,0,0,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,IR1,Lvl,AllPub,Inside,...,34,0,0,0,0,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,IR1,Lvl,AllPub,Inside,...,36,0,0,0,0,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,IR1,HLS,AllPub,Inside,...,82,0,0,144,0,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,Reg,Lvl,AllPub,Inside,...,24,0,0,0,0,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,Reg,Lvl,AllPub,Inside,...,0,0,0,0,0,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,Reg,Lvl,AllPub,Inside,...,32,0,0,0,0,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,Reg,Lvl,AllPub,Inside,...,48,0,0,0,0,0,11,2006,WD,Normal

In [26]:
# filling null values
print(test["LotFrontage"].mean()) 
test["LotFrontage"]=test["LotFrontage"].fillna(68) # not permanent so use inplace=True or save it

68.58035714285714

In [27]:
test.isnull().sum()

Id               0
MSSubClass       0
MSZoning         4
LotFrontage      0
LotArea          0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         1
SaleCondition    0
Length: 80, dtype: int64

In [28]:
print(test['MSZoning'].mode())
test['MSZoning']=test['MSZoning '].fillna("S")

0    RL
Name: MSZoning, dtype: str

KeyError: 'MSZoning '

In [24]:
#encoding converting catagorical into numerical
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

In [ ]:
test[""]